// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz2kdQriAT7glXlCaGc_VXQpJIx-4S578',
    appId: '1:796129169536:web:ec114d137a1ea9a7cd9665',
    messagingSenderId: '796129169536',
    projectId: 'e-book-app-6c882',
    authDomain: 'e-book-app-6c882.firebaseapp.com',
    storageBucket: 'e-book-app-6c882.firebasestorage.app',
    measurementId: 'G-YKME1B8729',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqhqz6goO07d3s1q6nRA9ppDsXyiahAB8',
    appId: '1:796129169536:android:f679303989e76c32cd9665',
    messagingSenderId: '796129169536',
    projectId: 'e-book-app-6c882',
    storageBucket: 'e-book-app-6c882.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBxhKYZ9Bxue6A6D5-DhBWOa8NK7vaOjA',
    appId: '1:796129169536:ios:90872dd8b4b28d0ccd9665',
    messagingSenderId: '796129169536',
    projectId: 'e-book-app-6c882',
    storageBucket: 'e-book-app-6c882.firebasestorage.app',
    iosBundleId: 'com.example.eBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBxhKYZ9Bxue6A6D5-DhBWOa8NK7vaOjA',
    appId: '1:796129169536:ios:90872dd8b4b28d0ccd9665',
    messagingSenderId: '796129169536',
    projectId: 'e-book-app-6c882',
    storageBucket: 'e-book-app-6c882.firebasestorage.app',
    iosBundleId: 'com.example.eBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz2kdQriAT7glXlCaGc_VXQpJIx-4S578',
    appId: '1:796129169536:web:025b95792ea4b023cd9665',
    messagingSenderId: '796129169536',
    projectId: 'e-book-app-6c882',
    authDomain: 'e-book-app-6c882.firebaseapp.com',
    storageBucket: 'e-book-app-6c882.firebasestorage.app',
    measurementId: 'G-DQGDX2XKZE',
  );
}
